CREATE DATABASE ACTIVIDAD
GO
USE ACTIVIDAD
CREATE TABLE CARRERAS(
ID VARCHAR(4) NOT NULL PRIMARY KEY,
Nombre VARCHAR(20) NOT NULL,
FechaCreacion DATE NOT NULL CHECK(FechaCreacion < GETDATE()),
Mail VARCHAR(20) NOT NULL UNIQUE,
Nivel VARCHAR(10) NOT NULL CHECK(Nivel='Diplomatura' OR Nivel='Pregrado'OR Nivel='Grado' OR Nivel='Posgrado' )
)
GO
CREATE TABLE ALUMNOS(
Legajo BIGINT NOT NULL PRIMARY KEY IDENTITY(1000,1),
IDCarrera VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES CARRERAS(ID),
Apellidos VARCHAR(20) NOT NULL,
Nombres VARCHAR(20) NOT NULL,
FechaNacimiento DATE NOT NULL CHECK(FechaNacimiento < GETDATE()),
Mail VARCHAR(20) NOT NULL UNIQUE,
Telefono VARCHAR(10) NULL
)
GO
CREATE TABLE MATERIAS(
Id BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDCarrera VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES CARRERAS(ID),
Nombres VARCHAR(20) NOT NULL,
CargaHoraria INT NOT NULL CHECK(CargaHoraria>0)
)